---
  - name: Prepare deb
    hosts: deb
    gather_facts: false
    tasks:
      - name: Install Python
        raw: apt-get update && apt-get install -y python3
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"